# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('timely', ['internet',
                                              'csma',
                                              'applications',
                                              'traffic-control',
                                              'point-to-point-layout'])
    module.source = [
			'model/timely-header.cc',
			'model/timely-receiver.cc',
			'model/timely-sender.cc',
			'model/timely-control.cc',
			'helper/timely-sender-receiver-helper.cc'
        ]

    module_test = bld.create_ns3_module_test_library('timely')
    module_test.source = [
        ]

    headers = bld(features='ns3header')
    headers.module = 'timely'
    headers.source = [
			'model/timely-header.h',
			'model/timely-receiver.h',
			'model/timely-sender.h',
            'model/timely-control.h',
			'model/timely-packet-filter.h',
			'helper/timely-sender-receiver-helper.h'
    ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

